export const FETCH_QUERYS_REQUEST = 'FETCH_QUERYS_REQUEST';
export const FETCH_QUERYS_SUCCESS = 'FETCH_QUERYS_SUCCESS';
export const FETCH_QUERYS_FAILURE = 'FETCH_QUERYS_FAILURE';
export const SET_QUERY = 'SET_QUERY';
export const ADD_QUERY = 'ADD_QUERY';
export const REMOVE_QUERY = 'REMOVE_QUERY';
