export const FETCH_VIEWS_REQUEST = 'FETCH_VIEWS_REQUEST';
export const FETCH_VIEWS_SUCCESS = 'FETCH_VIEWS_SUCCESS';
export const FETCH_VIEWS_FAILURE = 'FETCH_VIEWS_FAILURE';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
export const SAVE_VIEW_REQUEST = 'SAVE_VIEW_REQUEST';
export const SAVE_VIEW_SUCCESS = 'SAVE_VIEW_SUCCESS';
export const SAVE_VIEW_FAILURE = 'SAVE_VIEW_FAILURE';